### ISSUE TITLE
Provide an Auth_Sentry driver

### ISSUE THREAD

**Issue by hkdobrev** [cartalyst/sentry-kohana#4]
For maximum compatibility with an existing Kohana application using the Kohana Auth module, it would be great to have an auth driver for Sentry.

This way only the configuration in `application/config/auth.php` would need to change.

The driver would allow Kohana users to use the same `Auth::instance()->logged_in()` API, but under the hood this would use Sentry.

This would also be a great security improvement, as the default password hashing now is `sha256`.

**Comment by bencorlett** [comment]
sha256 is a terrible hashing algorithm, I’d never encourage it. In fact, we’ve just removed that from Sentry. `password_hash()` (using brcypt currently).

I’m all for somebody putting in a PR to make that driver-based functionality work, but we’re not really interested in coding that up. In fact, I don’t think the Sentry-Kohana package is near finished for Sentry 3, feel free to help us out there too :)
